name: Deploy to Raspberry Pi 4

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Déploiement de l'application Symfony
        run: |
          cd /var/www/matsiro
          git config --global --add safe.directory /var/www/matsiro

          # 1. Récupérer le dernier code
          git fetch origin main
          git reset --hard origin/main

          # 2. Supprimer manuellement le cache existant pour éviter les conflits d'autoloader
          rm -rf var/cache/*

          # 3. Installer les dépendances SANS exécuter les scripts automatiques
          composer install --no-dev --optimize-autoloader --no-scripts

          # 4. Nettoyer et réchauffer le cache pour la production
          php bin/console cache:clear --env=prod