name: Deploy to Raspberry Pi 4

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Déploiement de l'application Symfony
        run: |
          cd /var/www/matsiro
          git config --global --add safe.directory /var/www/matsiro
          
          # Récupération du code
          git fetch origin main
          git reset --hard origin/main

          # Installation des dépendances et vide du cache
          composer install --no-dev --optimize-autoloader --no-scripts
          php bin/console cache:clear --env=prod